### PR TITLE
Rearranging the simulation code

### PR DESCRIPTION
**Pull request by zaborowska**
1. Rearranging the directory structure (everything Geant-related in Sim/)
2. Simulation algorithm splitted, now:
      - Algorithm passes the event to and retrieves an event from service GeantSvc;
      - GeantSvc handles Geant configuration, owns a G4RunManager implementation;
3. Hits in sensitive volumes (tracker) are stored. Sensitive volumes/segmentation is defined in DD4hep.
4. Geometry set in GeantSvc via tool: can be either from DD4hep or from GDML, though the latter requires much more code-writing from the user (SD segmentation, filling the hits collections, magnetic field...)

### CODE REVIEW

**Comment by hegner** [comment]
Hi Anna. Which changes are still pending before you want to have it merged?

**Comment by zaborowska** [comment]
Hi, I think it's ready to be merged (hence pull req:)).
The two missing steps from restructuring side:
- splitting configuration tool into separate tools for physics list, user actions;
- merging algorithms for full/fast sim into one, with outputs set by tools (that after fix in Gaudi)
But that will just slightly change the configuration.

**Comment by hegner** [comment]
I was more asking whether there is outstanding feedback by Joschka. If not, I will test it now and if successful merge.

**Comment by zaborowska** [comment]
His corrections are already appplied.

**Pull request merged**
