### PR TITLE
FCC-EDM B-tag & Tau-tag information saved on the output & fixed MC truth output

### PR DESCRIPTION
**Pull request by drasal**
FCC-EDM B-tag & Tau-tag information saved on the output, tag information provided through jet<->tag relations. Several tags may be provided by different tagging algorithms (achievable due to relation mechanism applied in FCC-EDM). 

Comment: Functionality strictly dependent on the changes within the FCC-EDM 1.1->1.2 version! (fcc-edm PR #12)

In addition, the MC truth output to FCC-EDM has been fixed! One should be able to built the MC truth tree correctly.

Comments: If LHE event file was used on input to Pythia, then Pythia might have generated extra gluons which broke the ID numbering of daughters of primary colliding particles. To fix that a new algorithm has been implemented when transforming data from Delphes to FCC-EDM.

Tasks to be done within the next PR: 
* change raw pointers for smart pointers (under progress)

### CODE REVIEW

**Comment by cbernet** [comment]
Hi again, @drasal, could you please solve the conflict? thanks in advance

**Comment by jlingema** [comment]
retest this please

**Comment by jlingema** [comment]
Hi, in the meantime I reinstalled fcc-edm with the new tags on afs so the tests can work.

**Comment by jlingema** [comment]
retest this please

**Comment by drasal** [comment]
I have merged the changes in master branch with the changes on my side. Let's wait for the testing procedure ...

**Comment by drasal** [comment]
Added fix to MC truth output! One should be able to build the full MC truth tree correctly now.

**Comment by drasal** [comment]
Updated comments in PythiaDelphes configuration file.

**Comment by clementhelsens** [comment]
Merge thi PR to move on with DelphesSim

**Pull request merged**
