### PR TITLE
Pythia8 interface

### PR DESCRIPTION
**Pull request by shqiptare**
First version of a Pythia8 interface
- Generation/src/PythiaInterface.cpp
- Generation/src/PythiaInterface.h
- simple_pythia.py
- main03.cmnd

### CODE REVIEW

**Comment by cbernet** [comment]
Hi Ercan! Why are you closing and re-opening? Please let me know when the pull request is ready and I will test it again. 
Thanks, 

Colin

**Comment by shqiptare** [comment]
Hi Colin
Since there is not "pythia_ınterface" branch on the list, I thought to close the pull request and redo push.
Thanks,
Ercan

**Comment by cbernet** [comment]
No you should keep this one, I’m going to merge the changes in your branch into HEP-FCC/master.

**Comment by cbernet** [comment]
Hi Ercan, 

Did you get this last mail? 
Could you please finalize the pull request asap? I apologize if I have missed your update. 
If you are blocked for some reason, please let me know. 

Btw, do you think that you could present a working version of your pythia interface (with recipe for the users) at the meeting next week? 

Cheers! 

Colin

**Pull request merged**
