### PR TITLE
[WIP] Fix extrapolation

### PR DESCRIPTION
**Pull request by jhrdinka**
This pull request depends on PR #281 and should therefore be merged afterwards - marked as WIP for now. 

Addresses #260.

Changes proposed in this pull-request:
- Implements a configurable extrapolation tool which can later be used for both, reconstruction and extrapolation 
- Updates the extrapolation test to use the extrapolation tool
- Uses already the magnetic field 
- Hand over tracker material to tracking geometry
- Extrapolation uses now generated particles from the edm as input

### CODE REVIEW

**Comment by zaborowska** [comment]
@jhrdinka please have a look at the failing tests, as reported on [cdash](http://cdash.cern.ch/buildSummary.php?buildid=469840)

**Comment by JavierCVilla** [comment]
@phsft-bot build please

**Comment by JavierCVilla** [comment]
@phsft-bot build

**Comment by vvolkl** [comment]
Hi Julia,

* this writes out wrong positions not on any sensitive volume, even with all possible permutations of the options `CollectSensitive`, `CollectMaterial` and `CollectPassive`. I have to actually change the code to check for `associatedDetectorElement` to select the right extrapolationsteps
* Using the InterpolatedBFieldService, the extrapolated track is straight (compared to simulating the same particle with const b field )
* using the ConstantBFieldService, there is a segfault

**Comment by vvolkl** [comment]
Hi @jhrdinka,

it seems like you have a lot to do, but do you think you'll be able to address my comments above? Otherwise I propose we close this and I attempt to get a working extrapolation in a separate PR that isn't entangled with other open pull requests.
Cheers,
Valentin

**Comment by jhrdinka** [comment]
Hi @vvolkl,

I still need to finish other things, before I can address this PR again. It would be nice, if you could try to get it working. You could also start from this PR and we could rebase it onto master or, if you prefer open a new PR.

Cheers,
Julia

**Pull request closed without merging**
