### PR TITLE
Cast mag_driver for compatibility with Geant4 10.4

### PR DESCRIPTION
**Pull request by vvolkl**
This implements a workaround for a problem with `RenewStepperAndAdjust` in Geant4 10.4

### CODE REVIEW

**Comment by JavierCVilla** [comment]
@vvolkl I just tried it locally against Geant4-10.04 and it also requires to include a new header in order to use `G4MatInt_Driver`:

`#include G4MagIntegratorDriver.hh`

**Comment by JavierCVilla** [comment]
Just to bear in mind: Merging this would require to use the `LCG_93` release and for that IMHO it would be better to be compatible with `DD4hep-01.05`

**Comment by vvolkl** [comment]
Hi Javier, I think this solution is compatible works fine with the current stack, at least the tests are passing :)

**Comment by JavierCVilla** [comment]
@vvolkl Completely right, I though the `init.sh` script had been modified.

**Pull request merged**
