### PR TITLE
Only add trackid offset for tracker hits

### PR DESCRIPTION
**Pull request by vvolkl**
Fix for using the overlay algorithm on full detector events

### CODE REVIEW

**Comment by jhrdinka** [comment]
Hello Valentin, thank you for this pull request.
Unfortunately the problem seems not to be solved with just shifting the track IDs. (However it is fine, since the IDs are not used in the calo).
The problem is, that the track IDs of only the tracker can go up to nearly 60 Mio for one event already. Therefore we will have duplicated IDs and it is a "silent" problem, which we will not notice.
screen shot 2018-03-22 at 11 45 06

**Comment by jhrdinka** [comment]
Hi Valentin,
I am sorry, I did not see the hit counter. With that I guess it works. Anyway it is good to have it documented what the initial problem was above. I can test, if it is working now.

**Comment by zaborowska** [comment]
Hi @jhrdinka, did you test if it works (as you mention in the comment above)?

**Comment by vvolkl** [comment]
Closing this since MCTruth for a full 1000 pileup event is an edge case that is better handled differently. We should have an edm discussion at one point though

**Pull request closed without merging**
