### PR TITLE
adding particle generators

### PR DESCRIPTION
**Pull request by Ada15764**
Adding a set of classes that act as G4 particle generators (new files). no side effect is expected.

### CODE REVIEW

**Comment by hegner** [comment]
Hi! Would you have a ready-to-run example for it for testing?

**Comment by Ada15764** [comment]
yes, more stuff is coming...

andrea

**Comment by jlingema** [comment]
Hi Andrea,

Could you add the two new configs as tests in the [Examples](https://github.com/HEP-FCC/FCCSW/blob/master/Examples/CMakeLists.txt), please? 

Thanks,
Joschka

**Comment by jlingema** [comment]
retest this please

**Comment by clementhelsens** [comment]
Close this PR, conflicts merged in #102

**Pull request closed without merging**
