### PR TITLE
Adapt code to DD4hep v01.05

### PR DESCRIPTION
**Pull request by JavierCVilla**
Addresses a compatibility problem building against `DD4hep-1.05` due to `BitField64*`.

Changes proposed in this pull-request:

- Replace `BitField64` with the new threadsafe class `BitFieldCoder`.
- Keep using our implementation for segmentations (`GridEta`, `GridPhiEta` - previously renamed `FCCSWGridPhiEta` - , `GridRPhiEta`) since `DD4hep` has a bug calculating `eta` which causes failures in our tests. 

To be done **before merging this PR**:
- [x] Modify `init.sh` to source a stable stack of externals
- [x] Release a new version of the externals 
   + Done, new externals build against `LCG_93`

To be done **in a different PR**:

- [ ] Replace all our segmentations with the ones provided by DD4hep.
- [ ] PR to Include `GridEta` in DD4hep
- [x] PR to fix the `eta` calculation in `DD4hep`

### CODE REVIEW

**Comment by JavierCVilla** [comment]
@phsft-bot build

**Comment by JavierCVilla** [comment]
@vvolkl Thanks! Yes, I also think it should be merged as soon as possible to be aligned with the lcg releases. 

Thanks a lot to @zaborowska for all the help provided!

Jenkins has been reporting failures for this PR due to a memory limit issue when submitting tests to CDash, I already increased the parameter to allow bigger tests. However I think we should review the size of these tests at some point, the total `xml` file containing all the test outputs is around 70MB.

**Comment by vvolkl** [comment]
The failing test was due to a timeout and should be fixed with #304

**Comment by JavierCVilla** [comment]
This PR is ready to be merged.
+ Uses the new cvmfs software organization
+ `init.sh` sources the `93.0.0` FCC externals version
+ Uses `dd4hep-01.05`

**Comment by vvolkl** [comment]
Very nice, thanks @JavierCVilla!

**Pull request merged**
