### PR TITLE
Add CaloHitCollection to store cluster cells

### PR DESCRIPTION
**Pull request by kjvbrt**
Hello all,

this pull request fixes crash, which occurs when one wants to attach cells to the calo clusters.
I'm not sure this is the right way to do it, found it by experimentation :)

### CODE REVIEW

**Review by vvolkl — CHANGES_REQUESTED** [review]
Thanks for the patch! To make it easier to review, could you remove all the whitespace / formatting changes that don't touch change the actual code? You can reformat the code (best to run `clang-format`), but please do that in a separate commit or PR

**Comment by kjvbrt** [comment]
All unnecessary formmating was removed.
I'm not sure about the failed test, the error looks unrelated to me.

**Comment by BrieucF** [comment]
+1 

As discussed privately with @kjvbrt, some use case of this functionality do not need the attached cells to be stored permanently in the output rootfile (e.g. CorrectECalBarrelSliWinCluster). Transient storage can be investigated as a solution for that. Meanwhile, one can use `out.outputCommands = ["keep *", "drop CaloClusterCells"]` to save space in the output file if one do not need the attached cell for analysis

**Comment by vvolkl** [comment]
LGTM.  Only just now fixed the tests, will merge now and check them on the master branch.

**Review by vvolkl — APPROVED** [review]

**Pull request merged**
