### PR TITLE
Updated TileCal geometry for decrease in memory

### PR DESCRIPTION
**Pull request by CoralieNeubueser**
Changes proposed in this pull-request:

- new TileCal geometry in Barrel and extended Barrel of FCC-hh reference detector
- this replaces physical volumes in phi (modules) by dd4hep segmentation
- this also includes some updates in the toto-cluster and other reconstruction algorithms

The performance has been tested and validated against the CDR results, see slides:
https://indico.cern.ch/event/804169/contributions/3345075/attachments/1808759/2953123/20190308_newGeomValidation.pdf

### CODE REVIEW

**Comment by vvolkl** [comment]
@phsft-bot build

**Comment by CoralieNeubueser** [comment]
> Hi Coralie,
> 
> awesome, this solves a major software performance issue! and it seems from the validation plots that it is still a very good approximation. You could include in your slides these numbers, first for the old geometry:
> 
> ```
> ToolSvc.saveHCa...  DEBUG   5 hits are stored in a collection #0: HCalBarrelDetailedWedgeReadout
> MemStatAuditor       INFO Memory usage has changed after out Execute  virtual size = 5745.18 MB   resident set size = 5029.63 MB deltaVsize = 0  MB
> *****Chrono*****     INFO ****************************************************************************************************
> *****Chrono*****     INFO  The Final CPU consumption ( Chrono ) Table (ordered)
> *****Chrono*****     INFO ****************************************************************************************************
> Converter:Execute    INFO Time User   : Tot=   80 [ms] Ave/Min/Max=0.016(+-  0.4)/    0/   10 [ms] #=5000
> ParticleGun:Exe...   INFO Time User   : Tot=  250 [ms] Ave/Min/Max= 0.05(+-0.705)/    0/   10 [ms] #=5000
> out:Execute          INFO Time User   : Tot=  270 [ms] Ave/Min/Max=0.054(+- 1.91)/    0/  130 [ms] #=5000
> SimG4Alg:Execute     INFO Time User   : Tot=  450 [ms] Ave/Min/Max= 0.09(+-0.944)/    0/   10 [ms] #=5000
> ChronoStatSvc        INFO Time User   : Tot= 41.6  [s]                                             #=  1
> *****Chrono*****     INFO ****************************************************************************************************
> ```
> and for the new:
> 
> ```
> ToolSvc.saveHCa...  DEBUG   5 hits are stored in a collection #0: HCalBarrelReadout
> MemStatAuditor       INFO Memory usage has changed after SimG4Alg Execute   virtual size = 870.695 MB   resident set size = 154.746 MB deltaVsize = 0  MB
> *****Chrono*****     INFO ****************************************************************************************************
> Converter:Execute    INFO Time User   : Tot=   90 [ms] Ave/Min/Max=0.018(+-0.424)/    0/   10 [ms] #=5000
> ParticleGun:Exe...   INFO Time User   : Tot=  200 [ms] Ave/Min/Max= 0.04(+-0.631)/    0/   10 [ms] #=5000
> out:Execute          INFO Time User   : Tot=  340 [ms] Ave/Min/Max=0.068(+- 2.21)/    0/  150 [ms] #=5000
> SimG4Alg:Execute     INFO Time User   : Tot= 0.51  [s] Ave/Min/Max=0.000102(+-0.001)/    0/ 0.01  [s] #=5000
> ChronoStatSvc        INFO Time User   : Tot= 2.25  [s]                                             #=  1
> *****Chrono*****     INFO ****************************************************************************************************
> ```
> the difference is an order of magnitude in both runtime and memory consumption for the geometry construction, that's really not too bad :) This is for the barrel only though, I can check also for the extended barrel.

Thanks Valentin!
Yes, could you please check the memory decrease for the updated extended Barrel as well? 
Afterward, I will add that to the slides.

**Comment by vvolkl** [comment]
@phsft-bot build

**Comment by vvolkl** [comment]
With the extended barrel the difference is even more pronounced:
```
hcaldetailedwedge_geantino_scan.log:MemoryAuditor        INFO Memory usage before ParticleGun Execute virtual size = 8459.03 MB resident set size = 7751.38 MB
hcaldetailedwedge_geantino_scan.log:MemoryAuditor        INFO Memory usage has changed after ParticleGun Execute virtual size = 8459.03 MB resident set size = 7751.58 MB
hcaldetailedwedge_geantino_scan.log:MemoryAuditor        INFO Memory usage has changed after out Execute virtual size = 8469.18 MB resident set size = 7753.14 MB
hcaldetailedwedge_geantino_scan.log:MemoryAuditor        INFO Memory usage before ParticleGun Execute virtual size = 8469.18 MB resident set size = 7753.2 MB
hcal_geantino_scan.log:MemoryAuditor        INFO Memory usage before ParticleGun Execute virtual size = 868.504 MB resident set size = 160.828 MB
hcal_geantino_scan.log:MemoryAuditor        INFO Memory usage has changed after ParticleGun Execute virtual size = 868.504 MB resident set size = 161.039 MB
hcal_geantino_scan.log:MemoryAuditor        INFO Memory usage has changed after Converter Execute virtual size = 868.504 MB resident set size = 161.172 MB
hcal_geantino_scan.log:MemoryAuditor        INFO Memory usage has changed after SimG4Alg Execute virtual size = 868.504 MB resident set size = 161.543 MB
hcal_geantino_scan.log:MemoryAuditor        INFO Memory usage has changed after out Execute virtual size = 879.395 MB resident set size = 163.238 MB
hcal_geantino_scan.log:MemoryAuditor        INFO Memory usage before ParticleGun Execute virtual size = 879.395 MB resident set size = 163.301 MB
```
and the runtime:
```
hcaldetailedwedge_geantino_scan.log:Converter:Execute    INFO Time User   : Tot=  100 [ms] Ave/Min/Max= 0.02(+-0.447)/    0/   10 [ms] #=5000
hcaldetailedwedge_geantino_scan.log:ParticleGun:Exe...   INFO Time User   : Tot=  160 [ms] Ave/Min/Max=0.032(+-0.565)/    0/   10 [ms] #=5000
hcaldetailedwedge_geantino_scan.log:out:Execute          INFO Time User   : Tot=  390 [ms] Ave/Min/Max=0.078(+- 1.85)/    0/  120 [ms] #=5000
hcaldetailedwedge_geantino_scan.log:SimG4Alg:Execute     INFO Time User   : Tot= 0.59  [s] Ave/Min/Max=0.000118(+-0.00108)/    0/ 0.01  [s] #=5000
hcaldetailedwedge_geantino_scan.log:ChronoStatSvc        INFO Time User   : Tot= 65.3  [s]                                             #=  1
hcal_geantino_scan.log:Converter:Execute    INFO Time User   : Tot=   60 [ms] Ave/Min/Max=0.012(+-0.346)/    0/   10 [ms] #=5000
hcal_geantino_scan.log:ParticleGun:Exe...   INFO Time User   : Tot=  240 [ms] Ave/Min/Max=0.048(+-0.691)/    0/   10 [ms] #=5000
hcal_geantino_scan.log:out:Execute          INFO Time User   : Tot=  330 [ms] Ave/Min/Max=0.066(+-  2.2)/    0/  150 [ms] #=5000
hcal_geantino_scan.log:SimG4Alg:Execute     INFO Time User   : Tot= 0.57  [s] Ave/Min/Max=0.000114(+-0.00106)/    0/ 0.01  [s] #=5000
hcal_geantino_scan.log:ChronoStatSvc        INFO Time User   : Tot= 2.43  [s]    
```

**Comment by vvolkl** [comment]
We seem to have discovered yet another git mystery. Locally I had no problems merging this branch into master. Investigating ...

**Comment by vvolkl** [comment]
Turned out to be just a ui problem :) While rebasing is the default, the option to merge with a merge commit was still there.

**Pull request merged**
