### PR TITLE
[WIP] First version of FCC-ee detector description

### PR DESCRIPTION
**Pull request by nalipour**

### CODE REVIEW

**Comment by jlingema** [comment]
Hi Nilou,

Can you remove the materials.xml and elements.xml and instead add any missing entries into the ones that are in `Detector/DetCommon/compact/`?

It would also be great if you could add a test that constructs the detector and checks for overlaps:
see the example  [here](https://github.com/HEP-FCC/FCCSW/blob/master/Examples/CMakeLists.txt#L71), adding another config like [printOverlap.py](https://github.com/HEP-FCC/FCCSW/blob/master/Examples/options/printOverlaps.py#L5) but changing the detector that is used. That way we can automatically test that the detector description works properly.

Cheers,
Joschka

**Comment by nalipour** [comment]
Dear Joschka,

Thanks for your comments. I have updated the materials and elements file. I have also added the printOverlap_FCCee.py to check the overlaps. Please let me know if I am missing anything else.

Cheers,
Nilou

**Comment by jlingema** [comment]
Hi Nilou,

Many thanks. Can you also add it as a test, like is done [here](https://github.com/HEP-FCC/FCCSW/blob/master/Examples/CMakeLists.txt#L71)? You just need to copy the whole `gaudi_add_test` and point it to the new python script as well as rename it (the first argument). That way we can do the automatic testing.

Cheers,
Joschka

**Comment by jlingema** [comment]
Thanks. The following allows us to test automatically.

test this please

**Comment by jlingema** [comment]
Superseded by #187

**Pull request closed without merging**
