### PR TITLE
Readout of TailCatcher corrected for complete eta coverage

### PR DESCRIPTION
**Pull request by CoralieNeubueser**
Changes proposed in this pull-request:

- the number of bits of the readout bitfield eta is increased

### CODE REVIEW

**Comment by vvolkl** [comment]
Hi @CoralieNeubueser!

in my mind it would be more natural to make `phi` an unsigned field, but there doesn't seem to be a convention, when I grep for this readout we currently have almost all with an unsigned, even `eta` which seems better to me to have it unsigned:

```

etector/DetFCChhHCalTile/compact/FCChh_HCalExtendedBarrel_TileCal.xml:     <id>system:4,type:2,module:9,row:8,layer:4,tile:2,eta:1,phi:10</id>
Detector/DetFCChhHCalTile/compact/FCChh_HCalExtendedBarrel_TileCal.xml:     <id>system:4,type:2,module:9,row:8,layer:4,tile:2,eta:10,phi:10</id>
Detector/DetFCChhHCalTile/compact/FCChh_HCalBarrel_TileCal.xml:     <id>system:4,module:7,row:9,layer:5,tile:2,eta:1,phi:10</id>
Detector/DetFCChhHCalTile/compact/FCChh_HCalBarrel_TileCal.xml:     <id>system:4,module:7,row:9,layer:5,tile:2,eta:9,phi:10</id>
Detector/DetFCChhCalDiscs/compact/Endcaps_coneCryo_calibration.xml:      <id>system:4,subsystem:1,type:3,subtype:3,layer:8,eta:10,phi:10</id>
Detector/DetFCChhCalDiscs/compact/Endcaps_coneCryo_calibration.xml:      <id>system:4,subsystem:1,type:3,subtype:3,layer:8,eta:10,phi:10</id>
Detector/DetFCChhCalDiscs/compact/Endcaps_coneCryo.xml:      <id>system:4,subsystem:1,type:3,subtype:3,layer:8,eta:10,phi:10</id>
Detector/DetFCChhCalDiscs/compact/Endcaps_coneCryo.xml:      <id>system:4,subsystem:1,type:3,subtype:3,layer:8,eta:10,phi:10</id>
Detector/DetFCChhCalDiscs/compact/Forward_coneCryo.xml:      <id>system:4,subsystem:1,type:3,subtype:3,layer:8,eta:11,phi:10</id>
Detector/DetFCChhCalDiscs/compact/Forward_coneCryo.xml:      <id>system:4,subsystem:1,type:3,subtype:3,layer:8,eta:11,phi:10</id>
Detector/DetFCChhCalDiscs/compact/Forward_coneCryo_calibration.xml:      <id>system:4,subsystem:1,type:3,subtype:3,layer:8,eta:11,phi:10</id>
Detector/DetFCChhCalDiscs/compact/Forward_coneCryo_calibration.xml:      <id>system:4,subsystem:1,type:3,subtype:3,layer:8,eta:11,phi:10</id>
Detector/DetFCChhECalInclined/compact/FCChh_ECalBarrel_Common.xml:      <id>system:4,cryo:1,type:3,subtype:3,layer:8,eta:9,phi:10</id>
Detector/DetFCChhECalInclined/compact/FCChh_ECalBarrel_Common_calibration.xml:      <id>system:4,cryo:1,type:3,subtype:3,layer:8,eta:9,phi:10</id>
Detector/DetFCChhECalSimple/compact/FCChh_ECalBarrel_Common.xml:      <id>system:4,ECAL_Cryo:1,bath:1,EM_barrel:1,active_layer:9,eta:9,phi:10</id>
Detector/DetFCChhECalSimple/compact/FCChh_ECalBarrel_Gflash.xml:      <id>system:4,ECAL_Cryo:1,bath:1,EM_barrel:1,active_layer:9,eta:-9,phi:-10</id>
Detector/DetFCChhMuonSimple/compact/FCChh_MuonSystemSimple.xml:      <id>system:7,eta:9,phi:-10</id>
Test/TestGeometry/data/Barrel_testCaloSD_phieta.xml:      <id>eta:-9,phi:-17,system:1</id>
Test/TestGeometry/data/Barrel_testCaloSD_rphiz.xml:      <id>system:1,z:14,r:9,phi:-18</id>
Test/TestGeometry/data/TestBoxCaloSD_3readouts.xml:      <id>phi:-8,eta:-8,system:1</id>
```

Do you want me to merge right now or should we take a moment to harmonize this?

**Comment by CoralieNeubueser** [comment]
Hi @vvolkl,
thanks for the comment, yes I can make is unsigned.. i need to assign an offset then, that's why I didn't include it yesterday. But I will update it to make it coherent with the other readouts.

**Comment by vvolkl** [comment]
test this please

**Comment by vvolkl** [comment]
@phsft-bot build

**Pull request merged**
