### PR TITLE
Release v0.11

### PR DESCRIPTION
**Pull request by vvolkl**
Preparation branch for a new release, discuss below!

PRs that should be merged for this release:
- [x] #359 
- [x] #351 
- [x] #347 
- [x] #327 
- [x] #336 

- [x] Wait for new externals and update `init.sh` accordingly

### CODE REVIEW

**Comment by vvolkl** [comment]
@phsft-bot  build

**Comment by vvolkl** [comment]
@phsft-bot build

**Comment by vvolkl** [comment]
@phsft-bot build

**Comment by JavierCVilla** [comment]
@phsft-bot build just on centos7/gcc8

**Pull request merged**
