### PR TITLE
Add EvtGen Plugin to Pythia Interface.

### PR DESCRIPTION
**Pull request by vvolkl**
Following pythia example main48, this adds the option to do decays with EvtGen.

### CODE REVIEW

**Comment by clementhelsens** [comment]
Thanks @vvolkl !

**Comment by donalrinho** [comment]
Hi all,

I have been having a look at the EvtGen options for the Pythia interface. I have run two processes:
```
./run fccrun Examples/options/pythia.py --Filename Generation/data/ee_Z_bbbar.cmd --filename FCCPythiaOutput.root -n 100000
```
and
```
./run fccrun Examples/options/pythia.py --Filename Generation/data/ee_Z_bbbar.cmd --doEvtGenDecays True --EvtGenDecayFile Generation/data/Bd2DstTauNu.dec --filename FCCPythiaOutput_Bd2DstTauNu.dec -n 100000
```
where the second run uses an EvtGen decay file for the B0 -> (D* -> (D0 -> K pi) pi) (tau -> pi pi pi nu) nu decay. When I look at the output of both jobs (specifically the `genParticles` container), I see an identical number of D*'s produced. 

For the EvtGen run, I expected that any B0's produced by Pythia would be decayed according to the EvtGen .dec file, which should then force the decays to go 100% to D* tau nu. Thus, the overall number of D*'s in the EvtGen run file should be larger.

This may not be a bug, but just wanted to raise it here so we can try to understand what it is doing. Thanks! Donal

**Comment by clementhelsens** [comment]
Thanks for checking the interface @donalrinho 
Are you sure that the file 

> Generation/data/Bd2DstTauNu.dec

exists?

if not it will take the default one:

https://github.com/HEP-FCC/FCCSW/blob/820881fb9836e5a9c0f0b8381399f829ccb3a044/Generation/src/components/PythiaInterface.h#L83

**Comment by donalrinho** [comment]
Hi @clementhelsens - yeah I checked in the output log and it shows:

```
EvtGen:Initializing EvtGen
EvtGen:Storing known decay models
EvtGen:Defining EvtBcToNPi model: Bc -> V + npi and Bc -> P + npi decays
from A.V. Berezhnoy, A.K. Likhoded, A.V. Luchinsky: Phys.Rev.D 82, 014012 (2010) and arXiV:1104.0808.
EvtGen:Main decay file name  :Generation/data/Bd2DstTauNu.dec
EvtGen:PDT table file name   :Generation/data/evt.pdl
EvtGen:In readDecayFile, reading:Generation/data/Bd2DstTauNu.dec
EvtGen:Mixing type integer set to 1
EvtGen:Done initializing EvtGen
EvtGen:In readDecayFile, reading:Generation/data/Bd2DstTauNu.dec
EvtGen:Redefined decay of B0
EvtGen:Redefined decay of anti-B0 in CDecay
EvtGen:Redefined decay of D*-
EvtGen:Redefined decay of D*+ in CDecay
EvtGen:Redefined decay of D0
EvtGen:Redefined decay of anti-D0 in CDecay
EvtGen:Redefined decay of tau+
EvtGen:Redefined decay of tau- in CDecay
```
It seems to read my custom .dec file without any issues. But then the output ROOT files appear to be the same whether I use EvtGen or not.

**Comment by vvolkl** [comment]
Hi @donalrinho, could you share your `Bd2DstTauNu.dec`, maybe  pushing it to a branch? Then I'll investigate this.

**Comment by donalrinho** [comment]
Hi @vvolkl - I tried to push to a branch but I'm getting permissions errors for some reason:
```
remote: Permission to HEP-FCC/FCCSW.git denied to donalrinho.
fatal: unable to access 'https://github.com/HEP-FCC/FCCSW.git/': The requested URL returned error: 403
```
I was trying to commit to a new branch `dhill_evtgen_tests` and doing:
```
git checkout -b dhill_evtgen_tests
git add Generation/data/Bd2DstTauNu.dec
git add Generation/data/Bc2TauNu.dec
git commit -m "Added DecFiles for testing of EvtGen plugin."
git push origin dhill_evtgen_tests
```

I'd like to add the Bc -> tau nu .dec file as well. When I use it, I don't find any increase in the number of Bc mesons in my output sample. When using EvtGen, I expected each generated event to contain a Bc which then decays to the specified final state. But it may be that EvtGen will only decay the Bc's that actually get produced in Pythia (so 0.04% of events).

**Comment by vvolkl** [comment]
Ah, it seems you have not forked the FCCSW repository yet. Can you do that (https://docs.github.com/en/github/getting-started-with-github/fork-a-repo) and then run the following in your local repository:

```
git remote rename origin upstream
git remote add origin  https://github.com/donalrinho/FCCSW.git
```

Then you should be able to push to your fork (to which `origin` now points to). Our tutorials/documentation has more details: https://hep-fcc.github.io/fcc-tutorials/developing-fcc-software/FccSoftwareGit.html#when-i-try-to-push-to-the-repository-i-get-an-authentication-error

Also, I notice you have a typo in your command
```
./run fccrun Examples/options/pythia.py --Filename Generation/data/ee_Z_bbbar.cmd --doEvtGenDecays True --EvtGenDecayFile Generation/data/Bd2DstTauNu.dec --filename FCCPythiaOutput_Bd2DstTauNu.dec -n 100000
```
This should read `--filename FCCPythiaOutput_Bd2DstTauNu`**`.root`** - maybe you were looking at the wrong output files? I'll take a look  once you have pushed the `*.dec` files.

**Comment by donalrinho** [comment]
I'll try forking, thanks! Also, the `.dec` was a typo when I ran, sorry. I changed it manually to `.root` after I ran it, so am picking up the right ROOT file.

**Comment by donalrinho** [comment]
OK cool the fork worked :) Here is my repo with the new `.dec` files added into `Generation/data`:
```
https://github.com/donalrinho/FCCSW
```

**Comment by clementhelsens** [comment]
Hello @vvolkl , @donalrinho , 

any developments on this issue?

**Comment by vvolkl** [comment]
So far  I only went back to to the pythia example on which this code is based and tried to see if I can spot any issues, but the code looks ok. I also don't necessarily see a difference in the output of that example with or without evtgen. So for me it's not a very obvious issue, sorry. I'll have to read up a bit more on evtgen, and that may take some time. We can maybe also discuss if we can use more of the LHCb tooling.

**Pull request merged**
